name: go_grpc
services:
  go_grpc_server:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 8080:8000
    networks:
      - net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
    networks:
      - net

volumes:
  mongo_volume:
    driver: local

networks:
  net:
    driver: bridge
