// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: products_explorer/productsexplorer/productsexplorer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRequest_SortingParam_SortType int32

const (
	ListRequest_SortingParam_PRICE_ASC         ListRequest_SortingParam_SortType = 0
	ListRequest_SortingParam_PRICE_DESC        ListRequest_SortingParam_SortType = 1
	ListRequest_SortingParam_NAME_ASC          ListRequest_SortingParam_SortType = 2
	ListRequest_SortingParam_NAME_DESC         ListRequest_SortingParam_SortType = 3
	ListRequest_SortingParam_CHANGE_COUNT_ASC  ListRequest_SortingParam_SortType = 4
	ListRequest_SortingParam_CHANGE_COUNT_DESC ListRequest_SortingParam_SortType = 5
	ListRequest_SortingParam_LAST_CHANGED_ASC  ListRequest_SortingParam_SortType = 6
	ListRequest_SortingParam_LAST_CHANGED_DESC ListRequest_SortingParam_SortType = 7
)

// Enum value maps for ListRequest_SortingParam_SortType.
var (
	ListRequest_SortingParam_SortType_name = map[int32]string{
		0: "PRICE_ASC",
		1: "PRICE_DESC",
		2: "NAME_ASC",
		3: "NAME_DESC",
		4: "CHANGE_COUNT_ASC",
		5: "CHANGE_COUNT_DESC",
		6: "LAST_CHANGED_ASC",
		7: "LAST_CHANGED_DESC",
	}
	ListRequest_SortingParam_SortType_value = map[string]int32{
		"PRICE_ASC":         0,
		"PRICE_DESC":        1,
		"NAME_ASC":          2,
		"NAME_DESC":         3,
		"CHANGE_COUNT_ASC":  4,
		"CHANGE_COUNT_DESC": 5,
		"LAST_CHANGED_ASC":  6,
		"LAST_CHANGED_DESC": 7,
	}
)

func (x ListRequest_SortingParam_SortType) Enum() *ListRequest_SortingParam_SortType {
	p := new(ListRequest_SortingParam_SortType)
	*p = x
	return p
}

func (x ListRequest_SortingParam_SortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListRequest_SortingParam_SortType) Descriptor() protoreflect.EnumDescriptor {
	return file_products_explorer_productsexplorer_productsexplorer_proto_enumTypes[0].Descriptor()
}

func (ListRequest_SortingParam_SortType) Type() protoreflect.EnumType {
	return &file_products_explorer_productsexplorer_productsexplorer_proto_enumTypes[0]
}

func (x ListRequest_SortingParam_SortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListRequest_SortingParam_SortType.Descriptor instead.
func (ListRequest_SortingParam_SortType) EnumDescriptor() ([]byte, []int) {
	return file_products_explorer_productsexplorer_productsexplorer_proto_rawDescGZIP(), []int{2, 1, 0}
}

type FetchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_products_explorer_productsexplorer_productsexplorer_proto_rawDescGZIP(), []int{0}
}

func (x *FetchRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type FetchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileChunk []byte `protobuf:"bytes,1,opt,name=fileChunk,proto3" json:"fileChunk,omitempty"`
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_products_explorer_productsexplorer_productsexplorer_proto_rawDescGZIP(), []int{1}
}

func (x *FetchResponse) GetFileChunk() []byte {
	if x != nil {
		return x.FileChunk
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paging  *ListRequest_PagingParam  `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	Sorting *ListRequest_SortingParam `protobuf:"bytes,2,opt,name=sorting,proto3" json:"sorting,omitempty"`
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_products_explorer_productsexplorer_productsexplorer_proto_rawDescGZIP(), []int{2}
}

func (x *ListRequest) GetPaging() *ListRequest_PagingParam {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListRequest) GetSorting() *ListRequest_SortingParam {
	if x != nil {
		return x.Sorting
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price       uint32                 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	ChangeCount uint32                 `protobuf:"varint,3,opt,name=changeCount,proto3" json:"changeCount,omitempty"`
	LastChanged *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=lastChanged,proto3" json:"lastChanged,omitempty"`
}

func (x *Product) Reset() {
	*x = Product{}
	if protoimpl.UnsafeEnabled {
		mi := &file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_products_explorer_productsexplorer_productsexplorer_proto_rawDescGZIP(), []int{3}
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetChangeCount() uint32 {
	if x != nil {
		return x.ChangeCount
	}
	return 0
}

func (x *Product) GetLastChanged() *timestamppb.Timestamp {
	if x != nil {
		return x.LastChanged
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Products []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_products_explorer_productsexplorer_productsexplorer_proto_rawDescGZIP(), []int{4}
}

func (x *ListResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type ListRequest_PagingParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Count uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ListRequest_PagingParam) Reset() {
	*x = ListRequest_PagingParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRequest_PagingParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest_PagingParam) ProtoMessage() {}

func (x *ListRequest_PagingParam) ProtoReflect() protoreflect.Message {
	mi := &file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest_PagingParam.ProtoReflect.Descriptor instead.
func (*ListRequest_PagingParam) Descriptor() ([]byte, []int) {
	return file_products_explorer_productsexplorer_productsexplorer_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ListRequest_PagingParam) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRequest_PagingParam) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListRequest_SortingParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sort []ListRequest_SortingParam_SortType `protobuf:"varint,1,rep,packed,name=sort,proto3,enum=api.ListRequest_SortingParam_SortType" json:"sort,omitempty"`
}

func (x *ListRequest_SortingParam) Reset() {
	*x = ListRequest_SortingParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRequest_SortingParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest_SortingParam) ProtoMessage() {}

func (x *ListRequest_SortingParam) ProtoReflect() protoreflect.Message {
	mi := &file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest_SortingParam.ProtoReflect.Descriptor instead.
func (*ListRequest_SortingParam) Descriptor() ([]byte, []int) {
	return file_products_explorer_productsexplorer_productsexplorer_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ListRequest_SortingParam) GetSort() []ListRequest_SortingParam_SortType {
	if x != nil {
		return x.Sort
	}
	return nil
}

var File_products_explorer_productsexplorer_productsexplorer_proto protoreflect.FileDescriptor

var file_products_explorer_productsexplorer_productsexplorer_proto_rawDesc = []byte{
	0x0a, 0x39, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x5f, 0x65, 0x78, 0x70, 0x6c, 0x6f,
	0x72, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x65, 0x78, 0x70, 0x6c,
	0x6f, 0x72, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x65, 0x78, 0x70,
	0x6c, 0x6f, 0x72, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x20, 0x0a, 0x0c, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x22, 0x2d, 0x0a, 0x0d, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x22, 0xa5, 0x03, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x34, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x52, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x12, 0x37, 0x0a, 0x07, 0x73, 0x6f, 0x72, 0x74,
	0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6f, 0x72, 0x74,
	0x69, 0x6e, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x69, 0x6e,
	0x67, 0x1a, 0x37, 0x0a, 0x0b, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0xed, 0x01, 0x0a, 0x0c, 0x53,
	0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x3a, 0x0a, 0x04, 0x73,
	0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6f, 0x72, 0x74,
	0x69, 0x6e, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x22, 0xa0, 0x01, 0x0a, 0x08, 0x53, 0x6f, 0x72, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x52, 0x49, 0x43, 0x45, 0x5f, 0x41, 0x53,
	0x43, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x49, 0x43, 0x45, 0x5f, 0x44, 0x45, 0x53,
	0x43, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x41, 0x4d, 0x45, 0x5f, 0x41, 0x53, 0x43, 0x10,
	0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x41, 0x4d, 0x45, 0x5f, 0x44, 0x45, 0x53, 0x43, 0x10, 0x03,
	0x12, 0x14, 0x0a, 0x10, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x43, 0x4f, 0x55, 0x4e, 0x54,
	0x5f, 0x41, 0x53, 0x43, 0x10, 0x04, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45,
	0x5f, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x44, 0x45, 0x53, 0x43, 0x10, 0x05, 0x12, 0x14, 0x0a,
	0x10, 0x4c, 0x41, 0x53, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x44, 0x5f, 0x41, 0x53,
	0x43, 0x10, 0x06, 0x12, 0x15, 0x0a, 0x11, 0x4c, 0x41, 0x53, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e,
	0x47, 0x45, 0x44, 0x5f, 0x44, 0x45, 0x53, 0x43, 0x10, 0x07, 0x22, 0x93, 0x01, 0x0a, 0x07, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64,
	0x22, 0x38, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x28, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x32, 0x75, 0x0a, 0x10, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x45, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x72, 0x12, 0x32,
	0x0a, 0x05, 0x46, 0x65, 0x74, 0x63, 0x68, 0x12, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x30, 0x01, 0x12, 0x2d, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x26, 0x5a, 0x24, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x5f,
	0x65, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x73, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_products_explorer_productsexplorer_productsexplorer_proto_rawDescOnce sync.Once
	file_products_explorer_productsexplorer_productsexplorer_proto_rawDescData = file_products_explorer_productsexplorer_productsexplorer_proto_rawDesc
)

func file_products_explorer_productsexplorer_productsexplorer_proto_rawDescGZIP() []byte {
	file_products_explorer_productsexplorer_productsexplorer_proto_rawDescOnce.Do(func() {
		file_products_explorer_productsexplorer_productsexplorer_proto_rawDescData = protoimpl.X.CompressGZIP(file_products_explorer_productsexplorer_productsexplorer_proto_rawDescData)
	})
	return file_products_explorer_productsexplorer_productsexplorer_proto_rawDescData
}

var file_products_explorer_productsexplorer_productsexplorer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_products_explorer_productsexplorer_productsexplorer_proto_goTypes = []interface{}{
	(ListRequest_SortingParam_SortType)(0), // 0: api.ListRequest.SortingParam.SortType
	(*FetchRequest)(nil),                   // 1: api.FetchRequest
	(*FetchResponse)(nil),                  // 2: api.FetchResponse
	(*ListRequest)(nil),                    // 3: api.ListRequest
	(*Product)(nil),                        // 4: api.Product
	(*ListResponse)(nil),                   // 5: api.ListResponse
	(*ListRequest_PagingParam)(nil),        // 6: api.ListRequest.PagingParam
	(*ListRequest_SortingParam)(nil),       // 7: api.ListRequest.SortingParam
	(*timestamppb.Timestamp)(nil),          // 8: google.protobuf.Timestamp
}
var file_products_explorer_productsexplorer_productsexplorer_proto_depIdxs = []int32{
	6, // 0: api.ListRequest.paging:type_name -> api.ListRequest.PagingParam
	7, // 1: api.ListRequest.sorting:type_name -> api.ListRequest.SortingParam
	8, // 2: api.Product.lastChanged:type_name -> google.protobuf.Timestamp
	4, // 3: api.ListResponse.products:type_name -> api.Product
	0, // 4: api.ListRequest.SortingParam.sort:type_name -> api.ListRequest.SortingParam.SortType
	1, // 5: api.ProductsExplorer.Fetch:input_type -> api.FetchRequest
	3, // 6: api.ProductsExplorer.List:input_type -> api.ListRequest
	2, // 7: api.ProductsExplorer.Fetch:output_type -> api.FetchResponse
	5, // 8: api.ProductsExplorer.List:output_type -> api.ListResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_products_explorer_productsexplorer_productsexplorer_proto_init() }
func file_products_explorer_productsexplorer_productsexplorer_proto_init() {
	if File_products_explorer_productsexplorer_productsexplorer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Product); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRequest_PagingParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRequest_SortingParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_products_explorer_productsexplorer_productsexplorer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_products_explorer_productsexplorer_productsexplorer_proto_goTypes,
		DependencyIndexes: file_products_explorer_productsexplorer_productsexplorer_proto_depIdxs,
		EnumInfos:         file_products_explorer_productsexplorer_productsexplorer_proto_enumTypes,
		MessageInfos:      file_products_explorer_productsexplorer_productsexplorer_proto_msgTypes,
	}.Build()
	File_products_explorer_productsexplorer_productsexplorer_proto = out.File
	file_products_explorer_productsexplorer_productsexplorer_proto_rawDesc = nil
	file_products_explorer_productsexplorer_productsexplorer_proto_goTypes = nil
	file_products_explorer_productsexplorer_productsexplorer_proto_depIdxs = nil
}
